import { copy, generatePlan, relativeDate, validDate } from "./clubOperations";
import type { Action, Copy, Goal, Plan, SourceId, SourceState } from "./clubOperations";

export type MatchSignal = { id: string; title: Copy; observation: Copy; territory: Copy; audience: Copy; effect: Copy; overlap: boolean; sharedAudience: boolean; accessImpact: boolean; opportunity: boolean; actionId: Action["id"]; recommendation: Copy; validation: Copy; sources: SourceId[] };
export function validKickoff(kickoff:string): boolean { return /^([01]\d|2[0-3]):[0-5]\d$/.test(kickoff); }
export function matchSignals(kickoff = "14:00"): MatchSignal[] {
  const minutes = validKickoff(kickoff) ? Number(kickoff.slice(0,2))*60+Number(kickoff.slice(3)) : -1000;
  const overlapsFootball = minutes < 17*60 && minutes + 120 > 15*60;
  const signals: MatchSignal[] = [
    { id:"football", title:copy("Fútbol masculino · coincidencia de horario", "Men’s football · overlapping time"), observation:copy("Partido ficticio de fútbol masculino durante la misma franja. Público compartido pendiente de validar.", "Fictional men's fixture in the same time window. Shared audience needs validation."), territory:copy("Zona de captación cercana", "Nearby catchment"), audience:copy("Seguidores de ambos equipos", "Followers of both teams"), effect:copy("Posible competencia por atención", "Possible attention competition"), overlap:true, sharedAudience:true, accessImpact:false, opportunity:false, actionId:"acquisition", recommendation:copy("Probar captación en segmentos con menor solapamiento y revisar el momento del mensaje.", "Test acquisition with lower-overlap segments and review message timing."), validation:copy("Confirmar horario, afinidad real y zonas antes de mover inversión. No reducir presupuesto automáticamente.", "Confirm time, actual affinity and areas before moving spend. Do not automatically cut budget."), sources:["ticketing"] },
    { id:"transport", title:copy("Movilidad · incidencia de ensayo", "Travel · rehearsal disruption"), observation:copy("Una ruta ficticia hacia el estadio tendría servicio reducido el día del partido.", "A fictional stadium route would have reduced service on matchday."), territory:copy("Corredor de acceso A · ficticio", "Access corridor A · fictional"), audience:copy("Asistentes que usan esa ruta", "Attendees using this route"), effect:copy("Fricción para llegar al estadio", "Stadium access friction"), overlap:true, sharedAudience:false, accessImpact:true, opportunity:false, actionId:"mobility", recommendation:copy("Preparar alternativas de llegada y una revisión de accesos antes del partido.", "Prepare travel alternatives and a pre-match access review."), validation:copy("Validar aviso oficial y audiencia afectada; no inferir rutas personales.", "Validate the official notice and affected audience; do not infer personal routes."), sources:["transport","crm"] },
    { id:"festival", title:copy("Festival próximo al estadio", "Festival near the stadium"), observation:copy("Evento ficticio con público distinto, pero posible presión sobre aparcamiento y transporte.", "Fictional event with a different audience but possible parking and transport pressure."), territory:copy("Entorno del estadio · ficticio", "Stadium surroundings · fictional"), audience:copy("Asistentes al partido", "Match attendees"), effect:copy("Impacto en accesos; no competencia demostrada", "Access impact; no proven competition"), overlap:true, sharedAudience:false, accessImpact:true, opportunity:false, actionId:"mobility", recommendation:copy("Añadir al briefing de llegada una comprobación de accesos y aparcamiento.", "Add access and parking checks to the travel briefing."), validation:copy("Comprobar magnitud, distancia y efecto real en accesos.", "Check scale, distance and actual access impact."), sources:["transport"] },
    { id:"community", title:copy("Encuentro de fútbol base local", "Local grassroots football gathering"), observation:copy("Actividad ficticia de una comunidad local antes del partido, con afinidad potencial.", "Fictional local community activity before the fixture, with potential affinity."), territory:copy("Barrio de captación B · ficticio", "Catchment neighbourhood B · fictional"), audience:copy("Comunidad y entidades locales", "Community and local organisations"), effect:copy("Oportunidad de colaboración", "Collaboration opportunity"), overlap:false, sharedAudience:true, accessImpact:false, opportunity:true, actionId:"partners", recommendation:copy("Preparar un borrador de colaboración con una entidad local.", "Prepare a collaboration draft with a local organisation."), validation:copy("Confirmar interés, capacidad, derechos y circuito específico si participan menores.", "Confirm interest, capacity, rights and a specialised process if minors participate."), sources:["ticketing","crm"] },
    { id:"weather", title:copy("Meteorología · lluvia de ejemplo", "Weather · example rain"), observation:copy("Previsión inventada de lluvia para ensayar comunicación práctica; no es una previsión actual.", "Invented rain forecast to rehearse practical communication; not a current forecast."), territory:copy("Estadio y accesos", "Stadium and access"), audience:copy("Personas con entrada o abono", "Ticket and season-pass holders"), effect:copy("Preparación de la asistencia", "Attendance preparation"), overlap:true, sharedAudience:true, accessImpact:false, opportunity:false, actionId:"attendance", recommendation:copy("Preparar información práctica sobre llegada y condiciones del recinto.", "Prepare practical arrival and venue information."), validation:copy("Revisar una previsión vigente y las indicaciones oficiales del recinto.", "Review a current forecast and official venue guidance."), sources:["weather","ticketing","crm","access"] },
    { id:"unrelated", title:copy("Concierto en otra zona", "Concert in another area"), observation:copy("Concierto ficticio sin público compartido identificado ni impacto conocido en accesos.", "Fictional concert with no identified shared audience or known access impact."), territory:copy("Otra zona de la ciudad", "Another city area"), audience:copy("Sin solapamiento identificado", "No identified overlap"), effect:copy("Contexto sin efecto material identificado", "Context with no material effect identified"), overlap:true, sharedAudience:false, accessImpact:false, opportunity:false, actionId:"acquisition", recommendation:copy("Mantener como contexto; no cambiar el plan por proximidad temporal únicamente.", "Keep as context; do not change the plan based on time proximity alone."), validation:copy("Reabrir solo si aparece evidencia de público compartido o impacto en accesos.", "Revisit only if shared-audience or access-impact evidence appears."), sources:[] },
  ];
  return signals.map(signal => signal.id === "football" ? { ...signal, overlap:overlapsFootball, observation:copy("Partido ficticio de fútbol masculino entre 15:00 y 17:00, en la zona horaria del club. Comparamos esa franja con las dos horas previstas de nuestro partido.", "Fictional men's fixture from 15:00 to 17:00 in the club time zone. We compare that window with our fixture's assumed two-hour duration."), effect:overlapsFootball ? signal.effect : copy("Sin coincidencia horaria en el ensayo", "No time overlap in the rehearsal") } : signal);
}
export function generateContextPlan(date:string, kickoff:string, fixtureId:string, goal:Goal, excluded:string[], sources:Record<SourceId,SourceState>, comprehensive=false, timeZone="Europe/London"): Plan {
  if (!validKickoff(kickoff)) throw new Error("Invalid kickoff");
  const signals = matchSignals(kickoff);
  const snapshot = signals.map(signal => ({ id:signal.id, state:excluded.includes(signal.id) ? "excluded" as const : !relevantSignal(signal) ? "irrelevant" as const : signal.sources.some(id=>sources[id]!=="ready") ? "unavailable" as const : "used" as const }));
  const base = generatePlan(date,goal,false,comprehensive);
  const plan = signals.filter(signal=>snapshot.find(s=>s.id===signal.id)?.state==="used").reduce(incorporateSignal,base);
  return { ...plan, kickoff, fixtureId, timeZone, sourceStates:{...sources}, actions:plan.actions.map(action=>({ ...action,fixtureContext:{fixtureId,kickoff,timeZone} })), excludedSignalIds:[...new Set(excluded)].sort(), signalSnapshot:snapshot };
}
export function relevantSignal(signal: MatchSignal): boolean { return signal.accessImpact || signal.opportunity || (signal.overlap && signal.sharedAudience); }
export function signalBlocker(signal: MatchSignal, plan: Plan | null, changed: boolean, sources: Record<SourceId, SourceState>): boolean {
  return !plan || changed || !validDate(plan.date) || !relevantSignal(signal) || signal.sources.some(id => sources[id] !== "ready") || Boolean(plan.actions.some(action => action.contextEvidence?.some(e => e.id === signal.id)));
}
export function incorporateSignal(plan: Plan, signal: MatchSignal): Plan {
  if (!relevantSignal(signal) || !validDate(plan.date)) return plan;
  const existing = plan.actions.find(action => action.id === signal.actionId);
  if (existing?.contextEvidence?.some(e => e.id === signal.id)) return plan;
  const template = generatePlan(plan.date, signal.actionId === "mobility" ? "attendance" : signal.actionId, signal.actionId === "mobility").actions.find(action => action.id === signal.actionId)!;
  const target = existing ?? template;
  const evidence = { id:signal.id, title:signal.title, recommendation:signal.recommendation, validation:signal.validation, reviewDate:relativeDate(plan.date,-3), synthetic:true as const };
  const next: Action = { ...target, sources:[...new Set([...target.sources,...signal.sources])], tasks:[...target.tasks,{ id:`${target.id}-signal-${signal.id}`, title:signal.validation, department:copy("Marketing", "Marketing"), offset:-3, owner:"", done:false }], approvedVersion:null, simulatedVersion:null, contextEvidence:[...(target.contextEvidence ?? []), evidence] };
  return { ...plan, actions:existing ? plan.actions.map(action => action.id === next.id ? next : action) : [...plan.actions,next] };
}
