import territoriesRaw from "../../data/seed/territories.json";
import fixturesRaw from "../../data/seed/fixtures.json";
import competitorsRaw from "../../data/seed/competitors.json";
import grassrootsRaw from "../../data/seed/grassroots.json";
import ticketingRaw from "../../data/seed/ticketing.json";
import calendarRaw from "../../data/seed/calendar.json";
import currentRaw from "../../data/live/current.json";
import signalsRaw from "../../data/live/signals.json";
import postmatchRaw from "../../data/live/postmatch.json";
import roadmapRaw from "../../data/live/roadmap.json";
import attendanceHistoryRaw from "../../data/history/attendance-2025-26.json";
import type { AttendanceHistory, CalendarFixture, Fixture, LiveSignal, Territory } from "./models";

export const territories = territoriesRaw as Territory[];
export const fixtures = fixturesRaw as Fixture[];
export const competitors = competitorsRaw;
export const grassroots = grassrootsRaw;
export const ticketing = ticketingRaw;
export const calendar = calendarRaw as CalendarFixture[];
export const currentState = currentRaw;
export const liveSignals = signalsRaw as LiveSignal[];
export const postmatchReviews = postmatchRaw;
export const roadmapItems = roadmapRaw;
export const attendanceHistory = attendanceHistoryRaw as AttendanceHistory;
