import territoriesRaw from "../../data/seed/territories.json";
import fixturesRaw from "../../data/seed/fixtures.json";
import competitorsRaw from "../../data/seed/competitors.json";
import grassrootsRaw from "../../data/seed/grassroots.json";
import ticketingRaw from "../../data/seed/ticketing.json";
import calendarRaw from "../../data/seed/calendar.json";
import clubActivationsRaw from "../../data/seed/club-activations.json";
import currentRaw from "../../data/live/current.json";
import signalsRaw from "../../data/live/signals.json";
import postmatchRaw from "../../data/live/postmatch.json";
import roadmapRaw from "../../data/live/roadmap.json";
import attendanceHistoryRaw from "../../data/history/attendance-2025-26.json";
import leagueAttendanceBenchmarkRaw from "../../data/live/wsl-attendance-benchmark.json";
import audienceReachRaw from "../../data/live/audience-reach.json";
import crmTicketingReadinessRaw from "../../data/live/crm-ticketing-readiness.json";
import crmTicketingDemoRaw from "../../data/demo/brighton-crm-ticketing.synthetic.json";
import campaignPlansRaw from "../../data/live/campaign-plans.json";
import searchDemandRaw from "../../data/live/search-demand.json";
import { buildPostMatchScorecards } from "./postmatch";
import type { AttendanceHistory, AudienceReachData, CalendarFixture, CampaignPlanData, ClubActivationDataset, CrmTicketingDemo, CrmTicketingReadiness, Fixture, LeagueAttendanceBenchmark, LiveSignal, PostMatchReview, SearchDemandData, Territory } from "./models";

export const territories = territoriesRaw as Territory[];
export const fixtures = fixturesRaw as Fixture[];
export const competitors = competitorsRaw;
export const grassroots = grassrootsRaw;
export const ticketing = ticketingRaw;
export const calendar = calendarRaw as CalendarFixture[];
export const clubActivations = clubActivationsRaw as ClubActivationDataset;
export const currentState = currentRaw;
export const liveSignals = signalsRaw as LiveSignal[];
export const postmatchReviews = postmatchRaw as PostMatchReview[];
export const roadmapItems = roadmapRaw;
export const attendanceHistory = attendanceHistoryRaw as AttendanceHistory;
export const leagueAttendanceBenchmark = leagueAttendanceBenchmarkRaw as LeagueAttendanceBenchmark;
export const audienceReach = audienceReachRaw as AudienceReachData;
export const crmTicketingReadiness = crmTicketingReadinessRaw as CrmTicketingReadiness;
export const crmTicketingDemo = crmTicketingDemoRaw as CrmTicketingDemo;
export const campaignPlans = campaignPlansRaw as CampaignPlanData;
export const searchDemand = searchDemandRaw as SearchDemandData;
export const postMatchScorecards = buildPostMatchScorecards(calendar, postmatchReviews, crmTicketingDemo);
