import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import ts from "typescript";
const read = p => readFile(new URL(`../${p}`,import.meta.url),"utf8");
const compile = s => ts.transpileModule(s,{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText;
const url = s => `data:text/javascript;base64,${Buffer.from(compile(s)).toString("base64")}`;
const operations = url((await read("src/lib/clubOperations.ts")).replace(/import sample from .*?;/,`const sample=${await read("data/seed/club-operations-demo.json")};`));
const {generatePlan,actionVersion} = await import(operations);
const context = (await read("src/lib/clubMatchContext.ts")).replace('from "./clubOperations";',`from "${operations}";`);
const {matchSignals,relevantSignal,incorporateSignal,signalBlocker} = await import(url(context));
const sources = {ticketing:"ready",crm:"ready",access:"ready",transport:"ready",weather:"ready"};
test("events require audience overlap or a concrete access or collaboration effect",()=>{
  const signals=matchSignals();
  assert.equal(signals.filter(relevantSignal).length,5);
  const unrelated=signals.find(s=>s.id==="unrelated");
  assert.equal(relevantSignal(unrelated),false);
  assert.equal(relevantSignal({...signals[0],overlap:false}),false);
  assert.equal(relevantSignal(signals.find(s=>s.id==="festival")),true);
});
test("signal drafts retain existing assignments, combine evidence, add dated tasks and are idempotent",()=>{
  const plan=generatePlan("2026-10-18","repeat",true);
  plan.actions[0].owner="marketing";
  plan.actions[1].approvedVersion="old";
  const original=JSON.stringify(plan);
  const added=incorporateSignal(plan,matchSignals().find(s=>s.id==="transport"));
  const merged=incorporateSignal(added,matchSignals().find(s=>s.id==="festival"));
  assert.equal(JSON.stringify(plan),original);
  assert.equal(merged.actions.length,2);
  assert.equal(merged.actions[0],plan.actions[0]);
  const mobility=merged.actions[1];
  assert.equal(mobility.contextEvidence.length,2);
  assert.equal(mobility.tasks.length,6);
  assert.equal(mobility.contextEvidence[0].reviewDate,"2026-10-15");
  assert.equal(mobility.approvedVersion,null);
  assert.notEqual(actionVersion(mobility,plan.date,sources),actionVersion(plan.actions[1],plan.date,sources));
  assert.equal(incorporateSignal(merged,matchSignals()[1]),merged);
});
test("weather adds a sourced attendance draft and stale context prevents incorporation",()=>{
  const plan=generatePlan("2026-10-18","repeat",false);
  const signal=matchSignals().find(s=>s.id==="weather");
  assert.equal(signalBlocker(signal,null,false,sources),true);
  assert.equal(signalBlocker(signal,plan,true,sources),true);
  assert.equal(signalBlocker(signal,plan,false,{...sources,weather:"stale"}),true);
  const added=incorporateSignal(plan,signal);
  assert.ok(added.actions[1].sources.includes("weather"));
  assert.equal(added.actions[1].owner,"");
  assert.equal(added.actions[1].measurement,false);
  assert.equal(signalBlocker(signal,added,false,sources),true);
});
test("batch suggestions group actions, exclude irrelevant events and do not grant approvals",()=>{
  const plan=generatePlan("2026-10-18","repeat",false);
  const next=matchSignals().filter(relevantSignal).reduce(incorporateSignal,plan);
  assert.equal(next.actions.length,5);
  assert.equal(new Set(next.actions.map(a=>a.id)).size,5);
  assert.equal(next.actions.flatMap(a=>a.contextEvidence??[]).length,5);
  assert.ok(next.actions.every(a=>!a.approvedVersion&&!a.simulatedVersion));
  assert.ok(next.actions.every(a=>!a.contextEvidence?.some(e=>e.id==="unrelated")));
});
