import { proposalChanges } from "@/lib/clubProposalChanges";
import { matchSignals } from "@/lib/clubMatchContext";
import { goalLabels, sourceLabels } from "@/lib/clubOperations";
import type { Locale, Plan } from "@/lib/clubOperations";
import styles from "./ClubOperationsDemo.module.css";

export function ClubPlanProposal({ suggestion, current, lang }: { suggestion:Plan; current:Plan|null; lang:Locale }) {
  const tr = (es:string,en:string) => lang === "es" ? es : en;
  const delta = proposalChanges(current,suggestion);
  const signals = matchSignals(suggestion.kickoff);
  const stateLabels = { used:tr("utilizada", "used"), excluded:tr("desactivada", "disabled"), irrelevant:tr("sin efecto relevante", "no relevant effect"), unavailable:tr("fuente no disponible", "source unavailable") };
  const groups = [ [tr("Aparecerían", "Would be added"),delta.added], [tr("Cambiarían", "Would change"),delta.updated], [tr("Desaparecerían", "Would be removed"),delta.removed] ] as const;
  return <section className={styles.content} aria-label={tr("Acciones sugeridas y comparación", "Suggested actions and comparison")}>
    {current && <div className={styles.panel}><h2>{tr("Qué cambiaría respecto al borrador vigente", "What would change from the current draft")}</h2>{delta.fixtureChanged && <p className={styles.warning}>{tr("Se ha cambiado el partido, la fecha o la hora. Revisa las ventanas y coincidencias del nuevo contexto.", "Fixture, date or time changed. Review timing and overlaps in the new context.")}</p>}{groups.filter(([,actions])=>actions.length).map(([label,actions])=><p key={label}><strong>{label}: </strong>{actions.map(action=>action.title[lang]).join(" · ")}</p>)}{!delta.added.length && !delta.updated.length && !delta.removed.length && <p>{tr("Las propuestas de acción no cambian con esta selección.", "Action proposals do not change with this selection.")}</p>}<p>{delta.unchanged.length} {tr("propuestas sin cambios", "unchanged proposals")} · {tr("Variación de tareas", "Task difference")}: {delta.taskDifference > 0 ? "+" : ""}{delta.taskDifference}.</p>{delta.signals.length > 0 && <ul>{delta.signals.map(signal=><li key={signal.id}>{signals.find(s=>s.id===signal.id)?.title[lang] ?? signal.id}: {signal.before ? stateLabels[signal.before] : tr("sin registro", "not recorded")} → {stateLabels[signal.after]}</li>)}</ul>}<p>{tr("Los cambios se aplican al confirmar. En el mismo partido se conservan responsables, tareas compatibles y textos editados. Las acciones modificadas requieren nueva revisión. Las que desaparecen se retiran con sus tareas y piezas. Cambiar de partido o club sustituye el borrador de esta sesión.", "Changes apply on confirmation. Within the same fixture, owners, compatible tasks and edited copy are preserved. Changed actions need a new review. Removed actions lose their tasks and assets. Changing fixture or club replaces this session’s draft.")}</p></div>}
    <div className={styles.panel}><h2>{tr("Acciones que propone el motor", "Actions proposed by the engine")}</h2><p>{tr("Borradores de prueba: explicamos el motivo y la medición, sin estimar ventas ni impacto garantizado.", "Test drafts: we explain rationale and measurement without estimating sales or guaranteed impact.")}</p><ol className={styles.proposalList}>{suggestion.actions.map(action=>{
      const unavailable = action.sources.filter(id=>suggestion.sourceStates?.[id]!=="ready");
      const evidence = action.contextEvidence ?? [];
      return <li key={action.id}><article><details><summary><h3>{action.title[lang]}</h3></summary>{(action.id===suggestion.goal || suggestion.comprehensive) && action.id!=="mobility" && <p><strong>{tr("Objetivo del club", "Club objective")}: </strong>{goalLabels[action.id][lang]}{action.id!==suggestion.goal ? tr(" · plan integral seleccionado", " · complete plan selected") : ""}.</p>}{evidence.length ? <><p><strong>{tr("Señales que la justifican", "Signals behind it")}: </strong>{evidence.map(e=>e.title[lang]).join(" · ")}</p><ul>{evidence.map(e=><li key={e.id}>{e.recommendation[lang]}</li>)}</ul></> : <p>{action.reason[lang]}</p>}{unavailable.length > 0 && <p className={styles.warning}>{tr("Aprobación bloqueada por datos pendientes", "Approval blocked by pending data")}: {unavailable.map(id=>sourceLabels[id][lang]).join(" · ")}. {tr("No aprobar ni lanzar hasta restaurar y revisar las fuentes.", "Do not approve or launch until sources are restored and reviewed.")}</p>}<details><summary>{tr("Audiencia, validación y medición", "Audience, validation and measurement")}</summary><dl className={styles.facts}><div><dt>{tr("Audiencia y exclusiones", "Audience and exclusions")}</dt><dd>{action.audience[lang]}</dd></div><div><dt>{tr("Qué falta validar", "Needs validation")}</dt><dd>{evidence.length ? <ul>{evidence.map(e=><li key={e.id}>{e.validation[lang]} · {e.reviewDate}</li>)}</ul> : tr("Confirmar datos, audiencia elegible, responsable y criterio de medición con el club.", "Confirm data, eligible audience, owner and measurement criteria with the club.")}</dd></div><div><dt>{tr("Cómo medir", "How to measure")}</dt><dd>{action.kpi[lang]}</dd></div></dl><p>{action.tasks.length} {tr("tareas propuestas · responsables y aprobaciones pendientes", "proposed tasks · owners and approvals pending")}</p></details></details></article></li>;
    })}</ol></div>
  </section>;
}
