"use client";

import { useState } from "react";
import { demoPolicy, evidenceIds, requiredReviews, reviewers } from "@/lib/clubControl";
import type { ControlEvent, ControlSettings, Review, ReviewKind } from "@/lib/clubControl";
import styles from "./ClubOperationsDemo.module.css";

type Props = { es: boolean; role: string; owner: string; version: string; settings: ControlSettings; paused: boolean; reviews: Review[]; events: ControlEvent[]; blockers: string[]; hasAction: boolean; onSettings: (value: ControlSettings) => void; onReview: (kind: ReviewKind, reviewer: string, evidence: string) => void; onPause: () => void; onRevoke: () => void; onExport: () => void };
export function ClubControlReview(p: Props) {
  const tr = (es: string, en: string) => p.es ? es : en;
  const [reviewer, setReviewer] = useState("compliance");
  const names: Record<ReviewKind, string> = { operations: tr("Operación y audiencia", "Operations and audience"), brand: tr("Marca y contenido", "Brand and content"), rights: tr("Derechos y cumplimiento", "Rights and compliance"), finance: tr("Presupuesto", "Budget") };
  const labels: Record<string,string> = {
    paused:tr("Operación pausada. No pueden lanzarse acciones.","Operation paused. No actions can launch."), policy:tr("Fecha fuera de la vigencia de la política de prueba.","Date outside test policy validity."), budget:tr("Presupuesto inválido.","Invalid budget."), purpose:tr("Permiso para esta finalidad retirado.","Permission for this purpose withdrawn."), minors:tr("Menores: bloqueado; falta un circuito específico validado por el club.","Minors: blocked; a club-validated specialised process is missing."), likeness:tr("Rostros o voces sintéticos: bloqueado; no hay proveedor ni permiso específico.","Synthetic faces or voices: blocked; no provider or specific permission."), creative:tr("Genera primero una pieza para revisar su versión exacta.","Generate a creative first to review its exact version."), reservation:tr("No existe una reserva social válida para este partido y territorio.","No valid social reservation for this fixture and territory."), agreement:tr("Acuerdo de talento no validado.","Talent agreement not validated."), dates:tr("Talento fuera de vigencia o disponibilidad.","Talent outside validity or availability."), channel:tr("El derecho reservado no cubre este canal. WhatsApp no hereda derechos sociales.","Reserved rights do not cover this channel. WhatsApp does not inherit social rights."), territory:tr("Territorio no autorizado.","Territory not authorised."), conflict:tr("Conflicto de categoría.","Category conflict."), quota:tr("Cupo desconocido o excedido.","Unknown or exceeded quota."), talentBudget:tr("El presupuesto no cubre el coste del talento.","Budget does not cover talent fee."), talent:tr("Talento no encontrado.","Talent not found.")
  };
  return <>
    <section className={styles.panel}><span className={styles.badge}>{tr("Incluido en licencia básica", "Included in base licence")}</span><h2>{tr("Control y cumplimiento", "Control and compliance")}</h2><p>{tr("Ficha por acción y versión de la pieza. Las evidencias y revisores son ficticios. No subas contratos ni datos privados.", "Review sheet per action and creative version. Evidence and reviewers are fictional. Do not upload contracts or private data.")}</p><p>{demoPolicy.id} · v{demoPolicy.version} · {demoPolicy.start} / {demoPolicy.end}</p><p>{tr("Política sintética de temporada, no normativa de LaLiga ni certificación. En producción el club debe validar país, competición, contratos y responsables.", "Synthetic season policy, not LaLiga rules or certification. In production the club must validate country, competition, contracts and owners.")}</p>
      <div className={styles.actions}><button type="button" disabled={p.role === "viewer"} onClick={p.onPause}>{p.paused ? tr("Reanudar ensayo · exige nuevas revisiones", "Resume rehearsal · new reviews required") : tr("Pausar todas las acciones", "Pause all actions")}</button><button type="button" disabled={p.role !== "approver" || !p.hasAction} onClick={p.onRevoke}>{tr("Revocar revisiones de esta acción", "Revoke this action's reviews")}</button></div>
      {!p.hasAction ? <p>{tr("Genera un plan para abrir su ficha de revisión.", "Generate a plan to open its review sheet.")}</p> : <><p>{tr("Configuración común del plan de ensayo. Cambiar estos criterios reinicia todas las fichas. Cada acción mantiene sus propias revisiones.", "Shared rehearsal plan settings. Changing these criteria resets all sheets. Each action keeps its own reviews.")}</p><div className={styles.fields}><label>{tr("Presupuesto de ensayo · unidades monetarias", "Rehearsal budget · currency units")}<input type="number" min="0" max="1000000" value={Number.isFinite(p.settings.budget) ? p.settings.budget : ""} disabled={p.role === "viewer"} onChange={(e) => p.onSettings({ ...p.settings, budget:e.target.value === "" ? NaN : Number(e.target.value) })} /></label><label>{tr("Revisor ficticio", "Fictional reviewer")}<select value={reviewer} onChange={(e) => setReviewer(e.target.value)}><option value="ticketing">Demo · Ticketing</option><option value="communications">Demo · Comunicación / Communications</option><option value="compliance">Demo · Compliance</option><option value="finance">Demo · Finanzas / Finance</option></select></label></div>
      <label className={styles.check}><input type="checkbox" checked={p.settings.purposeAllowed} disabled={p.role === "viewer"} onChange={(e) => p.onSettings({ ...p.settings, purposeAllowed:e.target.checked })} />{tr("Permiso de ejemplo para esta finalidad vigente", "Example permission for this purpose is current")}</label><label className={styles.check}><input type="checkbox" checked={p.settings.minors} disabled={p.role === "viewer"} onChange={(e) => p.onSettings({ ...p.settings, minors:e.target.checked })} />{tr("La acción incluye menores o cantera", "Action includes minors or academy players")}</label><label className={styles.check}><input type="checkbox" checked={p.settings.syntheticLikeness} disabled={p.role === "viewer"} onChange={(e) => p.onSettings({ ...p.settings, syntheticLikeness:e.target.checked })} />{tr("Solicita rostro o voz sintéticos", "Requests synthetic face or voice")}</label>
      <div className={styles.cards}>{requiredReviews(p.settings).map((kind) => { const review = p.reviews.find((r) => r.kind === kind && r.version === p.version); return <article className={styles.panel} key={kind}><h3>{names[kind]}</h3><span className={styles.badge}>{review ? tr("Validada en ensayo", "Validated in rehearsal") : tr("Pendiente", "Pending")}</span><p>{tr("Responsable de revisión", "Review owner")}: Demo · {reviewers[kind]}</p><p>{tr("Evidencia sintética", "Synthetic evidence")}: {evidenceIds[kind]}</p><p>{kind === "operations" ? tr("Finalidad, exclusiones, bajas y contacto limitado.", "Purpose, exclusions, opt-outs and contact cap.") : kind === "brand" ? tr("Kit, briefing, texto y uso del canal.", "Kit, brief, copy and channel use.") : kind === "rights" ? tr("Derechos, territorio, vigencia y exclusividades; no confirma contratos reales.", "Rights, territory, validity and exclusivity; does not confirm real contracts.") : tr("Importe y autoridad de gasto ficticios; no se realiza ningún cargo.", "Fictional amount and spending authority; no charge is made.")}</p><button type="button" disabled={p.paused || p.role !== "approver" || reviewer !== reviewers[kind] || reviewer === p.owner || !p.owner || review !== undefined || p.blockers.includes("creative")} onClick={() => p.onReview(kind,reviewer,evidenceIds[kind])}>{tr("Registrar revisión de prueba", "Record test review")}</button>{reviewer === p.owner && <p>{tr("El responsable de la acción no puede autoaprobar esta revisión.", "The action owner cannot self-approve this review.")}</p>}</article>; })}</div>
      <h3>{tr("Revalidación antes del lanzamiento", "Pre-launch revalidation")}</h3>{p.blockers.length ? <ul className={styles.warning}>{p.blockers.map((id) => <li key={id}>{labels[id] ?? `${tr("Revisión pendiente", "Pending review")}: ${names[id as ReviewKind] ?? id}`}</li>)}</ul> : <p>{tr("Controles de prueba completos. El lanzamiento sigue exigiendo acción y pieza aprobadas, fuentes disponibles y módulos habilitados.", "Test controls complete. Launch still requires action and creative approval, available sources and enabled modules.")}</p>}</>}
    </section>
    <section className={styles.panel}><h2>{tr("Datos e IA · límites del ensayo", "Data and AI · rehearsal boundaries")}</h2><ul><li>{tr("Datos sintéticos únicamente. Sin proveedor de IA conectado, entrenamiento ni datos privados enviados.", "Synthetic data only. No connected AI provider, training or private data sent.")}</li><li>{tr("Documentos y señales externas son entradas no confiables, nunca instrucciones ni autorizaciones.", "Documents and external signals are untrusted inputs, never instructions or authorisations.")}</li><li>{tr("Menores, datos de salud y biometría quedan fuera. No se habilitan mediante una casilla de aprobación.", "Minors, health data and biometrics are out of scope. An approval checkbox cannot enable them.")}</li><li>{tr("Control esencial incluido en la base. Supervisión avanzada: registro de tratamientos, evaluación de riesgos e incidentes; todavía no implementada.", "Essential control included in base. Advanced supervision: processing inventory, risk assessments and incidents; not implemented yet.")}</li></ul></section>
    <section className={styles.panel}><h2>{tr("Trazabilidad del ensayo", "Rehearsal traceability")}</h2><p>{tr("Registro estructurado en memoria. Se pierde al recargar; no es un historial persistente ni inmutable. La pausa no retira mensajes ya enviados ni afecta campañas externas.", "Structured in-memory log. Resets on reload; not persistent or immutable history. Pausing does not retract sent messages or affect external campaigns.")}</p><button type="button" onClick={p.onExport}>{tr("Exportar expediente sintético", "Export synthetic review dossier")}</button><ol>{p.events.slice(-15).reverse().map((entry) => <li key={entry.id}>{entry.at} · {entry.action} · {entry.event} · Demo {entry.actor} · {entry.evidence || "—"}</li>)}</ol></section>
  </>;
}
