"use client";

import { useState } from "react";
import { activationBlockers, allModules, baseScope, campaignBlockers, completeAppearance, contentInsights, contrast, demoCampaigns, demoPlayers, demoPosts, licenceProposal, modules, playerCapacity, recommendPlayers, reserveAppearance, strategySample, toggleModule } from "@/lib/clubStrategy";
import type { ActivationRequest, Appearance, BrandKit, Campaign, ContentFilter, ModuleId, Weights } from "@/lib/clubStrategy";
import type { Locale, Role } from "@/lib/clubOperations";
import styles from "./ClubOperationsDemo.module.css";

export type StrategyView = "brand" | "campaignKit" | "intelligence" | "talent" | "licence";
type Props = { view: StrategyView; lang: Locale; date: string; role: Role; brand: BrandKit; campaign: Campaign; enabled: ModuleId[]; appearances: Appearance[]; onBrand: (value: BrandKit) => void; onCampaign: (value: Campaign) => void; onModules: (value: ModuleId[]) => void; onAppearances: (value: Appearance[], playerId?: string) => void; onDownload: (content: string, name: string, type: string) => void; onNotice: (message: string) => void };

export function ClubStrategyModules({ view, lang, date, role, brand, campaign, enabled, appearances, onBrand, onCampaign, onModules, onAppearances, onDownload, onNotice }: Props) {
  const tr = (es: string, en: string) => lang === "es" ? es : en;
  const editable = role !== "viewer";
  const [filter, setFilter] = useState<ContentFilter>({ account: "club", platform: "instagram", format: "video" });
  const [metric, setMetric] = useState<"volume" | "rate">("rate");
  const [signalState, setSignalState] = useState("sample");
  const [category, setCategory] = useState("retail");
  const [scope, setScope] = useState("club-social");
  const [territory, setTerritory] = useState("UK");
  const [owner, setOwner] = useState("partnerships");
  const [budget, setBudget] = useState(500);
  const [manualPlayer, setManualPlayer] = useState(demoPlayers[1].id);
  const [weights, setWeights] = useState<Weights>({ fit: 40, balance: 40, engagement: 20 });
  const activeIntelligence = enabled.includes("intelligence") && signalState === "sample";
  const request: ActivationRequest = { date, category, channel: scope, territory, owner, budget };
  const eligible = recommendPlayers(demoPlayers, request, appearances, weights, demoPosts, activeIntelligence);
  const rows = contentInsights(demoPosts, filter, "playerId", metric);
  const themes = contentInsights(demoPosts, filter, "theme", "rate");
  const blockedLabel: Record<string, string> = {
    agreement:tr("Acuerdo sin firma o validación", "Agreement unsigned or unvalidated"), dates:tr("Fuera de vigencia o fecha inválida", "Outside validity or invalid date"), channel:tr("Canal no autorizado", "Channel not authorised"), territory:tr("Territorio no autorizado", "Territory not authorised"), conflict:tr("Conflicto de categoría", "Category conflict"), availability:tr("Disponibilidad sin confirmar", "Availability unconfirmed"), quotaUnknown:tr("Cupo pendiente de confirmar", "Quota unconfirmed"), quota:tr("Cupo agotado", "Quota exhausted"), collision:tr("Otra aparición ese día", "Another appearance that day"), budget:tr("Presupuesto insuficiente o inválido", "Budget insufficient or invalid"), owner:tr("Falta responsable", "Owner required")
  };
  const downloadJSON = (value: unknown, name: string) => onDownload(JSON.stringify(value, null, 2), name, "application/json");

  if (view === "brand") return <>
    <section className={styles.panel}><span className={styles.badge}>{tr("Incluido en gestión básica", "Included in basic management")}</span><h2>{tr("Identidad permanente del club", "Permanent club identity")}</h2><p>{tr("El Brand Kit base no cambia con cada campaña. Este ejemplo no contiene escudos ni recursos oficiales del club.", "The base Brand Kit does not change with each campaign. This sample contains no official club crests or assets.")}</p>
      <div className={styles.fields}><label>{tr("Nombre del kit de prueba", "Test kit name")}<input value={brand.name} maxLength={40} disabled={!editable} onChange={(e) => onBrand({ ...brand, name:e.target.value, version:brand.version+1 })} /></label><label>{tr("Tipografía de prueba", "Test typeface")}<select disabled={!editable} value={brand.font} onChange={(e) => onBrand({ ...brand, font:e.target.value as BrandKit["font"], version:brand.version+1 })}><option value="sans-serif">Sans serif</option><option value="serif">Serif</option></select></label><label>{tr("Color principal", "Primary colour")}<input type="color" value={brand.primary} disabled={!editable} onChange={(e) => onBrand({ ...brand, primary:e.target.value, version:brand.version+1 })} /></label><label>{tr("Color de fondo", "Background colour")}<input type="color" value={brand.background} disabled={!editable} onChange={(e) => onBrand({ ...brand, background:e.target.value, version:brand.version+1 })} /></label></div>
      <p>{tr("Versión", "Version")} {brand.version} · {tr("Contraste base", "Base contrast")} {contrast(brand.primary, brand.background).toFixed(1)}:1 · {tr("Tono", "Tone")}: {brand.tone}</p>
      <div className={styles.brandPreview} style={{ background:brand.background, color:brand.primary, fontFamily:brand.font }}><strong>{brand.name || tr("Kit sin nombre", "Unnamed kit")}</strong><p>{tr("Una identidad, distintas campañas.", "One identity, different campaigns.")}</p></div>
      <div className={styles.actions}><button type="button" onClick={() => downloadJSON(brand, "brand-demo.json")}>{tr("Descargar kit sintético", "Download synthetic kit")}</button><label>{tr("Adjuntar kit JSON de prueba · máx. 10 KB", "Attach test JSON kit · max 10 KB")}<input type="file" accept=".json,application/json" disabled={!editable} onChange={async (e) => { const file=e.target.files?.[0]; e.target.value=""; if (!file || !editable) return; if (file.size > 10000) { onNotice(tr("Archivo rechazado: máximo 10 KB.", "File rejected: maximum 10 KB.")); return; } try { const { parseDemoBrand } = await import("@/lib/clubStrategy"); const imported=parseDemoBrand(await file.text()); onBrand({ ...imported, version:brand.version+1 }); onNotice(tr("Kit sintético importado localmente; revisa las piezas de nuevo.", "Synthetic kit imported locally; review assets again.")); } catch { onNotice(tr("JSON rechazado. Usa el kit sintético descargado; no adjuntes recursos privados.", "JSON rejected. Use the downloaded synthetic kit; do not attach private assets.")); } }} /></label></div>
      <p>{tr("Lectura local, sin envío al servidor. Solo admite el esquema sintético de esta demo. PDFs, logos, fotografías, contratos y bibliotecas conectadas requieren el espacio privado; aquí no se aceptan.", "Local reading, no server upload. Only this demo's synthetic schema is supported. PDFs, logos, photographs, contracts and connected libraries require a private workspace; they are not accepted here.")}</p>
    </section><section className={styles.panel}><h2>{tr("Biblioteca conectada · pendiente", "Connected library · pending")}</h2><p>{tr("En producción: manual, escudos, fuentes licenciadas, material audiovisual, derechos y caducidades; conexión autorizada con el repositorio elegido por el club. Cada recurso tendrá versión y responsable.", "In production: manual, crests, licensed fonts, media, rights and expiry; authorised connection to the club's chosen repository. Each asset has a version and owner.")}</p><button type="button" disabled>{tr("Conexión privada todavía no disponible", "Private connection not yet available")}</button></section>
  </>;

  if (view === "campaignKit") return <>
    <section className={styles.panel}><h2>{tr("Dirección creativa de campaña", "Campaign creative direction")}</h2><p>{tr("Cada campaña conserva su concepto, vigencia y paleta sin modificar la identidad base. Cambiar cualquiera de los kits invalida las piezas anteriores del ensayo.", "Each campaign retains its concept, dates and palette without changing the base identity. Changing either kit invalidates previous rehearsal creatives.")}</p><label>{tr("Campaña de ejemplo", "Example campaign")}<select value={campaign.id} disabled={!editable} onChange={(e) => { const selected=demoCampaigns.find((item) => item.id === e.target.value); if(selected) onCampaign({ ...selected }); }}>{demoCampaigns.map((item) => <option key={item.id} value={item.id}>{item.name[lang]}</option>)}</select></label>
      <div className={styles.fields}><label>{tr("Titular de campaña", "Campaign headline")}<input value={campaign.headline[lang]} maxLength={40} disabled={!editable} onChange={(e) => onCampaign({ ...campaign, headline:{ ...campaign.headline, [lang]:e.target.value } })} /></label><label>{tr("Inicio", "Start")}<input type="date" value={campaign.start} disabled={!editable} onChange={(e) => onCampaign({ ...campaign, start:e.target.value })} /></label><label>{tr("Fin", "End")}<input type="date" value={campaign.end} disabled={!editable} onChange={(e) => onCampaign({ ...campaign, end:e.target.value })} /></label><label>{tr("Paleta de campaña", "Campaign palette")}<select value={campaign.primary} disabled={!editable} onChange={(e) => onCampaign({ ...campaign, primary:e.target.value, background:e.target.value === "#482955" ? "#f2e8f6" : "#e9f0df" })}><option value="#21432f">{tr("Verde · identidad de ejemplo", "Green · example identity")}</option><option value="#482955">{tr("Violeta · campaña de ejemplo", "Violet · example campaign")}</option></select></label></div>
      <label>{tr("Briefing de campaña", "Campaign brief")}<textarea value={campaign.brief[lang]} maxLength={500} rows={3} disabled={!editable} onChange={(e) => onCampaign({ ...campaign, brief:{ ...campaign.brief, [lang]:e.target.value } })} /></label>
      <p>{tr("Vinculada al partido de ensayo", "Linked to rehearsal fixture")}: {date} · {tr("La campaña añade su dirección creativa; el kit base mantiene la tipografía y el tono.", "The campaign adds its creative direction; the base kit retains typeface and tone.")}</p>
      {campaignBlockers(brand,campaign,date).length > 0 ? <p className={styles.warning}>{tr("No se puede generar: comprueba vigencia, briefing y contraste mínimo 4,5:1.", "Cannot generate: check validity, brief and minimum 4.5:1 contrast.")}</p> : <p className={styles.badge}>{tr("Configuración apta para generar una pieza de prueba", "Configuration ready for a test creative")}</p>}
      <div className={styles.brandPreview} style={{ background:campaign.background, color:campaign.primary, fontFamily:brand.font }}><strong>{campaign.headline[lang]}</strong><p>{campaign.name[lang]} · {brand.name}</p></div><button type="button" onClick={() => downloadJSON({synthetic:true,brand,campaign},"campaign-demo-brief.json")}>{tr("Descargar briefing de campaña", "Download campaign brief")}</button>
    </section><section className={styles.panel}><h2>{tr("Revisión de excepciones", "Exception review")}</h2><p>{tr("Este kit solo ensaya titulares, briefing y colores. En producción: recursos autorizados, formatos por canal, obligaciones de partners y aprobación de excepciones a la marca. No se verifican automáticamente todas las reglas de un manual.", "This kit rehearses headlines, brief and colours only. In production: licensed assets, channel formats, partner obligations and approval of brand exceptions. Not all manual rules are automatically checked.")}</p></section>
  </>;

  if (view === "intelligence") return <>
    <section className={styles.panel}><span className={styles.badge}>{tr("Módulo adicional · datos inventados", "Additional module · invented data")}</span><h2>{tr("Qué contenidos y protagonistas funcionan", "Which content and talent perform")}</h2><p>{tr("Nueve publicaciones ficticias, sin cuenta ni API conectada. Periodos comparables de prueba: 1–14 y 15–28 septiembre de 2026. Son muestras pequeñas: variación observada, no tendencia validada ni ventas atribuibles.", "Nine fictional posts, no account or API connected. Comparable test periods: 1–14 and 15–28 September 2026. Small samples: observed variation, not validated trends or attributable sales.")}</p>
      <div className={styles.fields}><label>{tr("Fuente de inteligencia", "Intelligence source")}<select value={signalState} onChange={(e) => setSignalState(e.target.value)}><option value="sample">{tr("Muestra sintética disponible", "Synthetic sample available")}</option><option value="stale">{tr("Simular datos desactualizados", "Simulate stale data")}</option><option value="missing">{tr("Simular ausencia de datos", "Simulate missing data")}</option></select></label><label>{tr("Cuenta de publicación", "Publishing account")}<select value={filter.account} onChange={(e) => setFilter({ ...filter, account:e.target.value as ContentFilter["account"] })}><option value="club">{tr("Cuenta del club · protagonista mencionado", "Club account · featured talent")}</option><option value="player">{tr("Cuenta del jugador", "Player account")}</option></select></label><label>{tr("Plataforma", "Platform")}<select value={filter.platform} onChange={(e) => setFilter({ ...filter, platform:e.target.value })}><option value="instagram">Instagram</option><option value="tiktok">TikTok</option></select></label><label>{tr("Formato comparable", "Comparable format")}<select value={filter.format} onChange={(e) => setFilter({ ...filter, format:e.target.value as ContentFilter["format"] })}><option value="video">{tr("Vídeo", "Video")}</option><option value="image">{tr("Imagen", "Image")}</option><option value="all">{tr("Todos · comparación exploratoria", "All · exploratory comparison")}</option></select></label><label>{tr("Métrica de ordenación", "Ranking metric")}<select value={metric} onChange={(e) => setMetric(e.target.value as typeof metric)}><option value="rate">{tr("Interacciones / impresiones", "Interactions / impressions")}</option><option value="volume">{tr("Volumen de interacciones", "Interaction volume")}</option></select></label></div>
      {!enabled.includes("intelligence") || signalState !== "sample" ? <p className={styles.warning}>{tr("Análisis no disponible: activa el módulo y restaura la muestra. El reparto de talento deja de usar engagement.", "Analysis unavailable: enable the module and restore the sample. Talent allocation stops using engagement.")}</p> : <>
      <div className={styles.tableWrap}><table><caption>{tr("Rendimiento del pool de prueba · tasa ponderada por impresiones, no media de porcentajes", "Test pool performance · impression-weighted rate, not an average of percentages")}</caption><thead><tr><th>{tr("Protagonista", "Talent")}</th><th>{tr("Posts", "Posts")}</th><th>{tr("Interacciones", "Interactions")}</th><th>{tr("Tasa", "Rate")}</th><th>{tr("Variación", "Change")}</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id}><td>{demoPlayers.find((p) => p.id === row.id)?.name}</td><td>{row.posts}</td><td>{row.interactions}</td><td>{row.rate === null ? tr("Denominador no disponible", "Denominator unavailable") : `${row.rate.toFixed(1)}%`}</td><td>{row.delta === null ? tr("Sin comparación", "No comparison") : `${row.delta > 0 ? "+" : ""}${row.delta.toFixed(1)} pp`}</td></tr>)}</tbody></table></div>{!rows.length && <p>{tr("Sin datos para estos filtros.", "No data for these filters.")}</p>}
      <h3>{tr("Temas y variaciones observadas", "Topics and observed changes")}</h3>{themes.map((theme) => <p key={theme.id}><strong>{theme.id}</strong> · {theme.posts} {tr("posts recientes", "recent posts")} · {theme.rate === null ? tr("Tasa desconocida", "Unknown rate") : `${theme.rate.toFixed(1)}%`} · {theme.delta === null ? tr("Sin base comparable", "No comparable baseline") : `${theme.delta > 0 ? "+" : ""}${theme.delta.toFixed(1)} pp`}</p>)}<p>{tr("Sugerencia: probar el tema con mejor tasa en una acción, tras validar objetivo, disponibilidad y derechos. No se publica ni se atribuyen compras a estas señales.", "Suggestion: test the highest-rate topic in an action after checking objective, availability and rights. Nothing is published and no purchases are attributed to these signals.")}</p></>}
    </section><section className={styles.panel}><h2>{tr("Blinkfire · conector previsto", "Blinkfire · planned connector")}</h2><p>{tr("Estado: NO CONECTADO. Datos requeridos: cuenta, post, fecha, formato, protagonista autorizado, métricas, denominador y procedencia. Campos, pool, histórico y frecuencia deben confirmarse en la API contratada.", "Status: NOT CONNECTED. Required data: account, post, date, format, authorised talent, metrics, denominator and provenance. Fields, pool, history and frequency must be confirmed in the contracted API.")}</p><p>{tr("No reemplaza a Blinkfire: convierte señales autorizadas en decisiones y flujos. Su licencia no está incluida. El uso multi-club o compartir resultados con terceros requiere confirmar permisos.", "Does not replace Blinkfire: turns authorised signals into decisions and workflows. Its licence is not included. Multi-club use or sharing results with third parties requires permission checks.")}</p><a href="https://www.blinkfire.com/connector/learnmore/gds" target="_blank" rel="noreferrer">{tr("Información oficial de acceso a API", "Official API access information")}</a><p><a href="https://www.blinkfire.com/api_tos" target="_blank" rel="noreferrer">{tr("Condiciones oficiales de API", "Official API terms")}</a></p><button type="button" onClick={() => downloadJSON(strategySample,"club-strategy-demo.json")}>{tr("Descargar datos y procedencia de prueba", "Download test data and provenance")}</button></section>
  </>;

  if (view === "talent") return <>
    <section className={styles.panel}><h2>{tr("Derechos, compromisos y capacidad", "Rights, commitments and capacity")}</h2><p>{tr("Registro manual incluido en la base; reparto ponderado en el módulo Talento. Todos los acuerdos y evidencias son ficticios: no hay contratos firmados reales ni interpretación legal automática.", "Manual register included in base; weighted allocation in Talent module. All agreements and evidence are fictional: no actual signed contracts or automated legal interpretation.")}</p><p>{tr("Una aparición es una unidad de este ensayo; derechos de imagen y apariciones personales son permisos distintos. No autoriza cuentas propias, publicidad pagada, réplicas digitales ni uso perpetuo salvo alcance explícito.", "An appearance is one unit in this rehearsal; image rights and personal appearances are distinct permissions. Own accounts, paid ads, digital replicas and perpetual use require explicit scope.")}</p>
      <div className={styles.tableWrap}><table><caption>{tr("Temporada 2026/27 · datos de prueba", "2026/27 season · test data")}</caption><thead><tr><th>{tr("Talento / acuerdo", "Talent / agreement")}</th><th>{tr("Vigencia", "Validity")}</th><th>{tr("Cupo", "Quota")}</th><th>{tr("Realizadas", "Completed")}</th><th>{tr("Reservadas", "Reserved")}</th><th>{tr("Restantes", "Remaining")}</th></tr></thead><tbody>{demoPlayers.map((player) => { const capacity=playerCapacity(player,appearances); return <tr key={player.id}><td><strong>{player.name}</strong><br />{player.signed && player.validated ? tr("Firma y alcance validados · simulados", "Signature and scope validated · simulated") : tr("Pendiente de validación", "Validation pending")}<br />{player.document}</td><td>{player.start}<br />{player.end}</td><td>{player.quota ?? tr("Sin confirmar", "Unconfirmed")}</td><td>{capacity.completed}</td><td>{capacity.reserved}</td><td>{capacity.remaining ?? "—"}</td></tr>; })}</tbody></table></div>
      <details><summary>{tr("Consultar alcance por jugador", "View scope by player")}</summary>{demoPlayers.map((p) => <p key={p.id}><strong>{p.name}</strong> · {p.channels.join(" / ")} · {p.territories.join(" / ")} · {tr("Categorías excluidas", "Excluded categories")}: {p.blockedCategories.join(", ") || "—"} · {tr("Coste ficticio por aparición", "Fictional cost per appearance")}: €{p.fee}</p>)}</details>
    </section>
    <section className={styles.panel}><h2>{tr("Repartir una activación", "Allocate an activation")}</h2><p>{tr("Fecha del partido de ensayo", "Rehearsal fixture date")}: <strong>{date}</strong>. {tr("Primero se filtran derechos y capacidad; después se pondera afinidad, equilibrio y engagement. No se usan datos médicos ni evaluaciones deportivas.", "Filter rights and capacity first; then weight fit, balance and engagement. No medical data or sporting assessments are used.")}</p><div className={styles.fields}>
      <label>{tr("Categoría del partner", "Partner category")}<select value={category} onChange={(e) => setCategory(e.target.value)}><option value="retail">{tr("Comercio", "Retail")}</option><option value="mobility">{tr("Movilidad", "Mobility")}</option></select></label><label>{tr("Uso solicitado", "Requested use")}<select value={scope} onChange={(e) => setScope(e.target.value)}><option value="club-social">{tr("Publicación orgánica del club", "Club organic social post")}</option><option value="event">{tr("Aparición presencial", "In-person appearance")}</option><option value="player-social">{tr("Publicación en cuenta propia", "Player's own account post")}</option><option value="paid-ad">{tr("Publicidad pagada", "Paid advertising")}</option></select></label>
      <label>{tr("Territorio", "Territory")}<select value={territory} onChange={(e) => setTerritory(e.target.value)}><option value="UK">UK</option><option value="ES">ES</option></select></label><label>{tr("Presupuesto ficticio por aparición (€)", "Fictional budget per appearance (€)")}<input type="number" min={0} max={10000} value={budget} onChange={(e) => setBudget(Number(e.target.value))} /></label><label>{tr("Responsable de activación", "Activation owner")}<select value={owner} onChange={(e) => setOwner(e.target.value)}><option value="">{tr("Sin asignar", "Unassigned")}</option><option value="partnerships">{tr("Responsable Demo · Partners", "Demo owner · Partnerships")}</option><option value="communications">{tr("Responsable Demo · Comunicación", "Demo owner · Communications")}</option></select></label></div>
      <h3>{tr("Registro manual · incluido en la base", "Manual register · included in base")}</h3><label>{tr("Elegir jugador manualmente", "Choose player manually")}<select value={manualPlayer} disabled={!editable} onChange={(e) => setManualPlayer(e.target.value)}>{demoPlayers.map((p) => <option value={p.id} key={p.id}>{p.name}</option>)}</select></label>{(() => { const player=demoPlayers.find((p) => p.id === manualPlayer)!; const blocked=activationBlockers(player,request,appearances); return <><p>{blocked.length ? blocked.map((reason) => blockedLabel[reason]).join(" · ") : tr("Elegible para el alcance solicitado; revisión humana necesaria.", "Eligible for requested scope; human review required.")}</p><button type="button" disabled={role !== "approver" || blocked.length > 0} onClick={() => { try { onAppearances(reserveAppearance(player,request,appearances,role),player.id); onNotice(tr("Reserva manual de prueba registrada. No hay compromiso externo.", "Manual test reservation recorded. No external commitment.")); } catch { onNotice(tr("Reserva bloqueada.", "Reservation blocked.")); } }}>{tr("Registrar reserva manual de prueba", "Record manual test reservation")}</button></>; })()}
      {!enabled.includes("talent") ? <p className={styles.warning}>{tr("Activa Talento en Licencia y módulos para añadir recomendaciones y reparto ponderado. El registro manual sigue disponible.", "Enable Talent in Licence & modules for recommendations and weighted allocation. Manual register remains available.")}</p> : <>
      <div className={styles.fields}>{(["fit","balance","engagement"] as const).map((key) => <label key={key}>{key === "fit" ? tr("Peso de afinidad", "Fit weight") : key === "balance" ? tr("Peso de equilibrio", "Balance weight") : tr("Peso de engagement", "Engagement weight")}<input type="range" min={key === "engagement" ? 0 : 1} max={100} disabled={key === "engagement" && !activeIntelligence} value={weights[key]} onChange={(e) => setWeights({ ...weights, [key]:Number(e.target.value) })} /><span>{key === "engagement" && !activeIntelligence ? tr("No usado · Inteligencia no disponible", "Not used · Intelligence unavailable") : weights[key]}</span></label>)}</div>
      <p>{tr("Puntuación: media ponderada de afinidad de ejemplo, porcentaje de cupo restante y tasa Instagram/vídeo × 10 (máximo 100). Pesos normalizados; no predice resultados. Tasa desconocida = sin evidencia, no rendimiento cero.", "Score: weighted average of sample fit, remaining quota percentage and Instagram/video rate × 10 (capped at 100). Normalised weights; no outcome prediction. Unknown rate means no evidence, not zero performance.")}</p>
      <div className={styles.cards}>{eligible.map(({player,capacity,rate,balance,score,blockers}) => <article key={player.id} className={styles.panel}><span className={styles.badge}>{blockers.length ? tr("No elegible", "Ineligible") : tr("Elegible en el ensayo", "Eligible in rehearsal")}</span><h3>{player.name}</h3><p>{tr("Puntuación orientativa", "Indicative score")}: {score.toFixed(1)} / 100</p><p>{tr("Afinidad", "Fit")}: {player.fit} · {tr("Equilibrio", "Balance")}: {balance.toFixed(0)}% · {tr("Engagement", "Engagement")}: {activeIntelligence && rate !== null ? `${rate.toFixed(1)}%` : tr("No usado / sin evidencia", "Not used / no evidence")}</p><p>{tr("Capacidad restante", "Remaining capacity")}: {capacity.remaining ?? tr("Desconocida", "Unknown")} · €{player.fee}</p>{blockers.length > 0 && <ul>{blockers.map((reason) => <li key={reason}>{blockedLabel[reason]}</li>)}</ul>}<button type="button" disabled={role !== "approver" || blockers.length > 0} onClick={() => { try { onAppearances(reserveAppearance(player,request,appearances,role),player.id); onNotice(tr("Reserva local registrada; no se ha contactado al jugador ni cerrado un acuerdo.", "Local reservation recorded; no player contacted or agreement executed.")); } catch { onNotice(tr("Reserva bloqueada. Revisa derechos y capacidad.", "Reservation blocked. Check rights and capacity.")); } }}>{tr("Aprobar y reservar en ensayo", "Approve and reserve in rehearsal")}</button></article>)}</div><p>{tr("Para reservar, selecciona el rol Aprobación. Cada reserva consume cupo y bloquea otra aparición del mismo jugador ese día.", "To reserve, select the Approver role. Each reservation consumes quota and blocks another appearance for the same player that day.")}</p></>}
    </section>
    <section className={styles.panel}><h2>{tr("Calendario de apariciones", "Appearance calendar")}</h2>{[...appearances].sort((a,b) => a.date.localeCompare(b.date)).map((a) => <article className={styles.appearance} key={a.id}><div><strong>{a.date} · {demoPlayers.find((p) => p.id === a.playerId)?.name}</strong><p>{a.category} · {a.channel} · {a.territory} · {a.owner}</p><p>{a.status === "completed" ? tr("Realizada · evidencia simulada", "Completed · simulated evidence") : a.status === "cancelled" ? tr("Cancelada · cupo liberado", "Cancelled · capacity released") : tr("Reservada · no realizada", "Reserved · not completed")}</p></div>{a.status === "reserved" && <div className={styles.actions}><button type="button" disabled={role !== "approver" || !enabled.includes("talent")} onClick={() => { onAppearances(completeAppearance(a.id,appearances,role)); onNotice(tr("Realización anotada con evidencia ficticia; no acredita una aparición real.", "Completion recorded with fictional evidence; does not prove an actual appearance.")); }}>{tr("Simular realización", "Simulate completion")}</button><button type="button" disabled={role !== "approver" || !enabled.includes("talent")} onClick={() => { onAppearances(appearances.map((item) => item.id === a.id ? { ...item,status:"cancelled" } : item)); onNotice(tr("Reserva cancelada; cupo liberado y piezas invalidadas.", "Reservation cancelled; capacity released and creatives invalidated.")); }}>{tr("Cancelar reserva de prueba", "Cancel test reservation")}</button></div>}</article>)}<button type="button" onClick={() => downloadJSON({synthetic:true,players:demoPlayers,appearances},"talent-activations-demo.json")}>{tr("Exportar registro sintético", "Export synthetic register")}</button></section>
  </>;

  return <>
    <section className={styles.panel}><span className={styles.badge}>{tr("Propuesta comercial · sin contratación", "Commercial proposal · no purchase")}</span><h2>{tr("Club Operations · licencia básica", "Club Operations · base licence")}</h2><p>{tr("Una base útil para coordinar el club; módulos según necesidades. Estos interruptores solo ensayan el alcance: no compran, cobran ni crean permisos reales.", "A useful base to coordinate the club; modules based on needs. These switches only rehearse scope: no purchases, billing or actual permissions.")}</p><ul>{baseScope.map((item) => <li key={item.en}>{item[lang]}</li>)}</ul><div className={styles.actions}><button type="button" disabled={!editable} onClick={() => onModules([])}>{tr("Probar solo licencia básica", "Try base licence only")}</button><button type="button" disabled={!editable} onClick={() => onModules(allModules)}>{tr("Probar todos los módulos", "Try all modules")}</button></div></section>
    <div className={styles.cards}>{modules.map((module) => <article className={styles.panel} key={module.id}><span className={styles.badge}>{enabled.includes(module.id) ? tr("Seleccionado en propuesta", "Selected in proposal") : tr("Adicional opcional", "Optional add-on")}</span><h2>{module.name[lang]}</h2><p>{module.value[lang]}</p><p>{module.scope[lang]}</p><p><strong>{tr("Requisitos de producción", "Production requirements")}: </strong>{module.production[lang]}</p><p><strong>{tr("Unidad comercial propuesta", "Proposed billing unit")}: </strong>{module.meter[lang]}</p>{module.dependency.length > 0 && <p>{tr("Requiere", "Requires")}: {module.dependency.map((id) => modules.find((m) => m.id === id)?.name[lang]).join(", ")}</p>}<label className={styles.check}><input type="checkbox" checked={enabled.includes(module.id)} disabled={!editable} onChange={(e) => onModules(toggleModule(enabled,module.id,e.target.checked))} />{tr("Incluir en propuesta de prueba", "Include in test proposal")}</label></article>)}</div>
    <section className={styles.panel}><h2>{tr("Tu configuración", "Your configuration")}</h2><p>Club Operations + {enabled.length ? modules.filter((m) => enabled.includes(m.id)).map((m) => m.name[lang]).join(" + ") : tr("sin módulos adicionales", "no additional modules")}</p><p>{tr("Automatización añade Audiencias; retirar Audiencias retira Automatización. Talento puede funcionar sin Inteligencia: entonces no usa engagement. Partners puede operar manualmente sin Blinkfire.", "Automation adds Audiences; removing Audiences removes Automation. Talent works without Intelligence, excluding engagement. Partners can operate manually without Blinkfire.")}</p><button type="button" onClick={() => downloadJSON(licenceProposal(enabled,lang),"club-licence-proposal.json")}>{tr("Descargar propuesta de alcance", "Download scope proposal")}</button></section>
    <section className={styles.panel}><h2>{tr("Modelo de contratación recomendado", "Recommended contracting model")}</h2><p>{tr("Suscripción anual por club + módulos. Implantación y conectores personalizados presupuestados aparte. Consumos variables con límites y alertas: IA, mensajes y publicidad. Usuarios adicionales por tramo; no cobrar por aficionado ni por partido en la base.", "Annual club subscription + modules. Onboarding and custom connectors quoted separately. Variable usage with caps and alerts: AI, messages and advertising. Additional users by tier; no per-fan or per-fixture charge in the base.")}</p><p>{tr("Sin tarifas publicadas todavía: validar tres pilotos pagados, coste de soporte/proveedores y disposición a pagar. Antes de una oferta: definir límites, almacenamiento, retención, soporte, renovación y salida/exportación.", "No published prices yet: validate three paid pilots, support/provider costs and willingness to pay. Before quoting: define limits, storage, retention, support, renewal and exit/export.")}</p><p className={styles.warning}>{tr("Disponibilidad actual: demo pública y local. Autenticación, almacenamiento privado, contratos reales, conectores, envíos e IA/vídeo de producción NO implementados. La propuesta no es una licencia activa ni garantiza resultados.", "Current availability: public local demo. Authentication, private storage, real agreements, connectors, delivery and production AI/video are NOT implemented. The proposal is not an active licence or an outcome guarantee.")}</p></section>
  </>;
}
