import type { Plan, SourceId, SourceState } from "@/lib/clubOperations";
import { actionVersion, goalLabels } from "@/lib/clubOperations";
import { rehearsalStage } from "@/lib/clubJourney";
import styles from "./ClubOperationsDemo.module.css";

export function ClubJourneyHome({ es, opponent, date, plan, sources, onPlan, onAction, onTasks }: { es: boolean; opponent: string; date: string; plan: Plan | null; sources: Record<SourceId, SourceState>; onPlan: () => void; onAction: (id: Plan["actions"][number]["id"]) => void; onTasks: () => void }) {
  const lang = es ? "es" : "en";
  const tr = (spanish: string, english: string) => es ? spanish : english;
  const pending = plan?.actions.flatMap(action => action.tasks).filter(task => !task.done).length ?? 0;
  const labels = { preparing: tr("En preparación", "Preparing"), review: tr("Pendiente de aprobación", "Awaiting approval"), approved: tr("Acción aprobada · faltan piezas y controles", "Action approved · assets and checks remain"), simulated: tr("Lanzamiento simulado", "Launch simulated") };
  return <>
    <section className={styles.panel}><p className={styles.eyebrow}>{tr("TU SIGUIENTE PASO", "YOUR NEXT STEP")}</p><h2>{plan ? tr("Continúa preparando las acciones", "Continue preparing your actions") : tr("Prepara el próximo partido", "Prepare the next fixture")}</h2><p>{opponent} · {plan?.date ?? date}</p><p>{plan ? tr("Abre una acción para ver su responsable, lo que falta y cómo continuar. Todo ocurre dentro del ensayo.", "Open an action to see its owner, remaining work and next step. Everything remains a rehearsal.") : tr("Elige el objetivo del partido. Te propondremos una acción inicial con sus tareas; podrás ampliar el plan después.", "Choose the fixture objective. Start with one proposed action and its tasks; expand the plan later.")}</p><button type="button" className={styles.primary} onClick={onPlan}>{plan ? tr("Ver el partido y su plan", "View fixture and plan") : tr("Preparar el partido", "Prepare fixture")}</button></section>
    {plan ? <><div className={styles.metrics}><article><span>{tr("Objetivo", "Objective")}</span><strong>{goalLabels[plan.goal][lang]}</strong></article><article><span>{tr("Acciones del ensayo", "Rehearsal actions")}</span><strong>{plan.actions.length}</strong></article><article><span>{tr("Tareas pendientes", "Pending tasks")}</span><strong>{pending}</strong><button type="button" onClick={onTasks}>{tr("Revisar tareas", "Review tasks")}</button></article></div><h2>{tr("Qué hacer ahora", "What to do now")}</h2><div className={styles.cards}>{plan.actions.map(action => <article className={styles.panel} key={action.id}><span className={styles.badge}>{labels[rehearsalStage(action, actionVersion(action, plan.date, sources))]}</span><h3>{action.title[lang]}</h3><p>{action.reason[lang]}</p><p>{tr("Responsable", "Owner")}: {action.owner || tr("Sin asignar", "Unassigned")}</p><button type="button" onClick={() => onAction(action.id)}>{tr("Abrir ficha de acción", "Open action sheet")}</button></article>)}</div></> : <section className={styles.panel}><h2>{tr("Así trabajarás", "How you will work")}</h2><ol><li>{tr("Define el objetivo y genera una propuesta para el partido.", "Define an objective and generate a fixture proposal.")}</li><li>{tr("Prepara audiencia, responsable y medición en la ficha de acción.", "Prepare audience, owner and measurement in the action sheet.")}</li><li>{tr("Revisa la acción, sus piezas y sus controles antes de simular el lanzamiento.", "Review the action, assets and checks before simulating delivery.")}</li></ol><p>{tr("No hay campañas activas ni resultados reales en esta demo.", "This demo has no active campaigns or real results.")}</p></section>}
  </>;
}
