import { matchSignals, relevantSignal, signalBlocker } from "@/lib/clubMatchContext";
import type { MatchSignal } from "@/lib/clubMatchContext";
import type { Locale, Plan, SourceId, SourceState } from "@/lib/clubOperations";
import styles from "./ClubOperationsDemo.module.css";

export function ClubMatchContext({ lang, date, plan, changed, editable, sources, dismissed, onAdd, onPrepare, onDismiss }: { lang:Locale; date:string; plan:Plan|null; changed:boolean; editable:boolean; sources:Record<SourceId,SourceState>; dismissed:string[]; onAdd:(signal:MatchSignal)=>void; onPrepare:()=>void; onDismiss:(id:string)=>void }) {
  const tr = (es:string,en:string) => lang === "es" ? es : en;
  return <section aria-label={tr("Contexto y señales", "Context and signals")}>
    <div className={styles.panel}><h2>{tr("Contexto y señales del partido", "Match context and signals")}</h2><p>{tr("Ejemplos sintéticos vinculados a la fecha de ensayo", "Synthetic examples linked to the rehearsal date")}: {date}. {tr("No son eventos, territorios ni previsiones reales de London City. Sin fuentes externas conectadas.", "These are not actual London City events, territories or forecasts. No external sources connected.")}</p><p>{tr("Primero genera el plan. Después revisa cada señal e incorpora las sugerencias pertinentes: se conservarán las acciones existentes y se añadirán tareas de validación sin responsable.", "Generate the plan first. Then review each signal and incorporate relevant suggestions: existing actions are retained and unassigned validation tasks are added.")}</p><p>{tr("La competencia exige coincidencia y público compartido; la movilidad y las colaboraciones se evalúan por separado. Todas las hipótesis tienen confianza baja hasta validarlas.", "Competition requires overlap and shared audience; travel and collaboration are assessed separately. All hypotheses have low confidence until validated.")}</p></div>
    <div className={styles.panel}><button type="button" className={styles.primary} disabled={!editable || !matchSignals().some(signal => !dismissed.includes(signal.id) && !signalBlocker(signal,plan,changed,sources))} onClick={onPrepare}>{tr("Preparar borradores desde señales", "Prepare drafts from signals")}</button><p>{tr("Procesa las sugerencias pertinentes y disponibles, excepto las descartadas. Agrupa las que afectan a la misma acción y conserva su evidencia. Requiere un plan generado y vigente.", "Processes relevant available suggestions, excluding dismissed ones. Groups suggestions affecting the same action and retains their evidence. Requires a current generated plan.")}</p></div>
    <details className={styles.panel}><summary>{tr("Revisar 6 señales de ejemplo y sus decisiones", "Review 6 example signals and decisions")}</summary><div className={styles.cards}>{matchSignals().map(signal => {
      const added = Boolean(plan?.actions.some(action => action.contextEvidence?.some(e => e.id === signal.id)));
      const dismissedSignal = dismissed.includes(signal.id);
      return <article key={signal.id} className={styles.panel}><span className={styles.badge}>{tr("Fuente: escenario ficticio · confianza baja", "Source: fictional scenario · low confidence")}</span><h3>{signal.title[lang]}</h3><p>{signal.observation[lang]}</p><dl className={styles.facts}><div><dt>{tr("Zona", "Area")}</dt><dd>{signal.territory[lang]}</dd></div><div><dt>{tr("Público", "Audience")}</dt><dd>{signal.audience[lang]}</dd></div><div><dt>{tr("Efecto", "Effect")}</dt><dd>{signal.effect[lang]}</dd></div></dl><h4>{tr("Sugerencia de decisión", "Suggested decision")}</h4><p>{signal.recommendation[lang]}</p><p><strong>{tr("Falta validar", "Needs validation")}: </strong>{signal.validation[lang]}</p><p>{tr("Revisión programada al incorporar: 3 días antes del partido. No hay un aviso actualizado de un proveedor.", "Scheduled review on incorporation: 3 days before the fixture. No updated provider notice is available.")}</p>{added ? <p>{tr("Incorporada al plan · pendiente de revisión y aprobación", "Incorporated into plan · review and approval pending")}</p> : !relevantSignal(signal) ? <p>{tr("Solo contexto · no genera acción", "Context only · no action generated")}</p> : <><p>{dismissedSignal ? tr("Descartada en esta sesión", "Dismissed in this session") : signalBlocker(signal,plan,changed,sources) ? tr("Genera un plan con la configuración vigente y comprueba las fuentes necesarias antes de incorporar.", "Generate a plan with the current settings and check required sources before incorporating.") : tr("Disponible para incorporar al plan como borrador", "Ready to incorporate into the plan as a draft")}</p><div className={styles.actions}><button type="button" disabled={!editable || dismissedSignal || signalBlocker(signal,plan,changed,sources)} onClick={()=>onAdd(signal)}>{tr("Incorporar sugerencia", "Incorporate suggestion")}</button><button type="button" disabled={!editable} onClick={()=>onDismiss(signal.id)}>{dismissedSignal ? tr("Reconsiderar", "Reconsider") : tr("Descartar", "Dismiss")}</button></div></>}</article>;
    })}</div></details>
  </section>;
}
