import { matchSignals } from "@/lib/clubMatchContext";
import type { Locale, Plan } from "@/lib/clubOperations";
import styles from "./ClubOperationsDemo.module.css";
import { ClubPlanProposal } from "./ClubPlanProposal";

export function ClubMatchContext({ lang, date, kickoff, timeZone, plan, suggestion, changed, editable, excluded, onPrepare, onToggle }: { lang:Locale; date:string; kickoff:string; timeZone:string; plan:Plan|null; suggestion:Plan|null; changed:boolean; editable:boolean; excluded:string[]; onPrepare:()=>void; onToggle:(id:string)=>void }) {
  const tr = (es:string,en:string) => lang === "es" ? es : en;
  const signals = matchSignals(kickoff);
  const labels = { used:tr("Se tendrá en cuenta", "Will be considered"), excluded:tr("Desactivada para este partido", "Disabled for this fixture"), irrelevant:tr("Solo contexto · sin efecto relevante", "Context only · no relevant effect"), unavailable:tr("Fuente necesaria no disponible · no genera propuesta", "Required source unavailable · no proposal") };
  const used = suggestion?.signalSnapshot?.filter(s=>s.state==="used") ?? [];
  return <section aria-label={tr("Contexto y señales", "Context and signals")}>
    <div className={styles.panel}><h2>{tr("Propuesta desde el partido y sus señales", "Proposal from the fixture and its signals")}</h2><p>{date || tr("Fecha pendiente", "Date pending")} · {kickoff || tr("Hora pendiente", "Time pending")} · {timeZone}</p><p>{tr("El motor analiza el contexto antes de crear un plan. Activa o desactiva señales para este partido y genera el borrador directamente.", "The engine analyses context before creating a plan. Enable or disable signals for this fixture and generate the draft directly.")}</p><p>{tr("Señales sintéticas de ensayo, sin fuentes externas conectadas. El calendario es la versión cargada del proyecto, sin sincronización en directo. No son eventos ni previsiones reales de London City.", "Synthetic rehearsal signals with no external feeds connected. Calendar is the project's stored version, with no live sync. These are not actual London City events or forecasts.")}</p>
    {suggestion ? <p><strong>{tr("Propuesta calculada", "Calculated proposal")}: </strong>{used.length} {tr("señales pertinentes disponibles", "relevant available signals")} · {suggestion.actions.length} {tr("acciones sugeridas", "suggested actions")}.</p> : <p>{tr("Completa una fecha y hora válidas para calcular la propuesta.", "Enter a valid date and time to calculate the proposal.")}</p>}
    <button type="button" className={styles.primary} disabled={!editable || !suggestion} onClick={onPrepare}>{plan ? tr("Recalcular borrador desde señales", "Recalculate draft from signals") : tr("Generar borrador desde señales", "Generate draft from signals")}</button>
    <p>{tr("El objetivo del club orienta una acción base; las señales añaden las propuestas pertinentes. Las desactivadas, irrelevantes o no disponibles se excluyen. Recalcular sustituye tareas y revisiones tras confirmación.", "The club objective guides a base action; signals add relevant proposals. Disabled, irrelevant or unavailable signals are excluded. Recalculation replaces tasks and reviews after confirmation.")}</p>
    {plan?.signalSnapshot && <p><strong>{tr("Señales utilizadas en el borrador vigente", "Signals used in the current draft")}: </strong>{plan.signalSnapshot.filter(s=>s.state==="used").map(s=>signals.find(signal=>signal.id===s.id)?.title[lang]).join(" · ") || tr("Ninguna; solo objetivo del club", "None; club objective only")}{changed ? tr(" · Cambios pendientes de recalcular", " · Changes awaiting recalculation") : ""}</p>}
    </div>
    {suggestion && <ClubPlanProposal suggestion={suggestion} current={plan} lang={lang} />}
    <details className={styles.panel}><summary>{tr("Ver señales y elegir cuáles utilizar", "View signals and choose which to use")} · {signals.length}</summary><div className={styles.cards}>{signals.map(signal => {
      const state = suggestion?.signalSnapshot?.find(s=>s.id===signal.id)?.state;
      return <article key={signal.id} className={styles.panel}><span className={styles.badge}>{tr("Fuente: escenario ficticio · confianza baja", "Source: fictional scenario · low confidence")}</span><h3>{signal.title[lang]}</h3><label className={styles.check}><input type="checkbox" checked={!excluded.includes(signal.id)} disabled={!editable} onChange={()=>onToggle(signal.id)} aria-label={tr("Usar señal para este partido", "Use signal for this fixture")+": "+signal.title[lang]} />{tr("Usar para este partido", "Use for this fixture")}</label><p><strong>{state ? labels[state] : tr("Pendiente de fecha y hora", "Awaiting date and time")}</strong></p><p>{signal.observation[lang]}</p><dl className={styles.facts}><div><dt>{tr("Zona", "Area")}</dt><dd>{signal.territory[lang]}</dd></div><div><dt>{tr("Público", "Audience")}</dt><dd>{signal.audience[lang]}</dd></div><div><dt>{tr("Efecto", "Effect")}</dt><dd>{signal.effect[lang]}</dd></div></dl><h4>{tr("Decisión sugerida", "Suggested decision")}</h4><p>{signal.recommendation[lang]}</p><p><strong>{tr("Falta validar", "Needs validation")}: </strong>{signal.validation[lang]}</p><p>{tr("Revisión programada: 3 días antes del partido. Hipótesis pendiente de validación.", "Scheduled review: 3 days before the fixture. Hypothesis awaiting validation.")}</p></article>;
    })}</div></details>
  </section>;
}
